### ISSUE TITLE
Lost ability to mine stone with wood or stone pickaxe

### ISSUE THREAD

**Issue by archonsd** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#1]
As soon as I add this mod to new SSP or my existing SMP minecraft games I lose the ability to mine stone with wood or stone pickaxes.  I can dig up dirt with my hands, or a stone pickaxe.  I can dig trees with my hand, or a pickaxe.  But I cannot mine stone in existing worlds where I could before adding this mod, and in new worlds I create just to test this mod.  I see a LOT of recipe errors in the attached log file from Slabs and Stairs.

I can replicate the issue with nothing but fabric and this mod in a brand new world.

Minecraft: 1.19.0
Fabric API:  0.57.0+1.19
Fabric Loader 0.14.8
Slabs and Stairs 1.0

Log file with a lot of other mods.  Will make another comment with a cleaner log of just fabric and this mod shortly.

[2022-07-17-3.log.gz](https://github.com/FrostbyteGames1/Frostbytes-Slabs-and-Stairs/files/9127174/2022-07-17-3.log.gz)

**Comment by archonsd** [comment]
Log file with just slabs and stairs and fabric.

[latest.log](https://github.com/FrostbyteGames1/Frostbytes-Slabs-and-Stairs/files/9127176/latest.log)

**Comment by FrostbyteGames1** [comment]
> As soon as I add this mod to new SSP or my existing SMP minecraft games I lose the ability to mine stone with wood or stone pickaxes. I can dig up dirt with my hands, or a stone pickaxe. I can dig trees with my hand, or a pickaxe. But I cannot mine stone in existing worlds where I could before adding this mod, and in new worlds I create just to test this mod.

I haven't been able to replicate this on my end, could you try running the 1.0.1 version (it should be available on Modrinth) and providing the log? What exactly do you mean by not being able to mine stone? Is it like bedrock, where it can't be mined at all, or is it taking a long time and/or not dropping anything?

> I see a LOT of recipe errors in the attached log file from Slabs and Stairs.

Thank you for catching this, it has been resolved in version 1.0.1.

**Comment by archonsd** [comment]
> 

I will try 1.0.1 as you requested.  To answer you question:

Mining stone with either a wooden pickaxe, or a stone pickaxe, behaves exactly like bare handed mining of stone..  where it takes a long, long time, but you can successfully remove the block..  but nothing drops.  It's like the wood or stone pickaxe is not recognized, and I'm mining the stone bare handed.

**Comment by archonsd** [comment]
Confirmed, with 1.0.1 I can mine on existing worlds and new worlds with stone and wood pickaxes again.

Thank you for the quick turnaround, @FrostbyteGames1 !
