### ISSUE TITLE
[Fabric] [1.20.1] Crash on "Singleplayer"

### ISSUE THREAD

**Issue by Deleca7755** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#13]
https://mclo.gs/W42EEuI
[crash-2024-06-20_22.40.08-client.txt](https://github.com/user-attachments/files/15922099/crash-2024-06-20_22.40.08-client.txt)

**Comment by FrostbyteGames1** [comment]
This should now be fixed as of v.1.7.2.
