### ISSUE TITLE
Recipe Conflict : Copper Button Prevents Decompression of Copper Blocks Into Ingots.

### ISSUE THREAD

**Issue by Ghostipedia** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#3]
Copper Button recipe makes it impossible by default to return 9 copper ingots from a block of copper, without a 3rd party mod or datapack.

Expected Result
1 Copper Block -> 9 Copper Ingots
Current Result
1 Copper Block -> 1 Copper Button

**Comment by FrostbyteGames1** [comment]
>I used the vanilla recipe patterns when creating the recipes for the new blocks. As a consequence, some vanilla crafting recipes may have been overwritten. I recommend using a mod or datapack that allows you to choose between multiple outputs from the same recipe, such as this one: https://www.curseforge.com/minecraft/mc-mods/polymorph-1-19-port-fabric

**Comment by Ghostipedia** [comment]
Ah I see, my apologies, I did look into polymorph but I only found versions for 1.18.2 Tsym!
