### ISSUE TITLE
Server Crash when user interacts with the Sawmill

### ISSUE THREAD

**Issue by Wash113** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#4]
Hey! I am getting a server crash when the Sawmill is used. Doesn't occur on a singleplayer world with the same modlist as the server runs. Here is the [crash log](https://gist.github.com/Wash113/78fe8329ecf6354c73f3d1815d62d157)

**Comment by FrostbyteGames1** [comment]
Thanks for bringing this to my attention, I'll take a look at it this week

**Comment by FrostbyteGames1** [comment]
Update: I believe this should be fixed now. Feel free to download version 1.2.1 or above and test for yourself. (It is available right now on Modrinth, but will most likely be until Monday for it to be approved on CurseForge).
