### ISSUE TITLE
Please allow the sawmill to craft from wooden slabs

### ISSUE THREAD

**Issue by adambenson** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#5]
Please expand the available recipes on the sawmill to include those made with wooden slabs.
The stonecutter does this for stone types and gives an incentive to use the stonecutter over the crafting table by lowering the material cost for stairs.
If we want to craft wooden slabs or stairs we must still use the crafting table.
It would be a good incentive to use the sawmill for these and also seems more logical.

**Comment by FrostbyteGames1** [comment]
I have released version 1.4.1, which allows for crafting regular slabs, stairs, and planks with the sawmill block.

**Comment by adambenson** [comment]
Champion! Thank you so much for the prompt response.
