### ISSUE TITLE
Slabs do not break with pickaxe

### ISSUE THREAD

**Issue by markmoser** [FrostbyteGames1/Frostbytes-Slabs-and-Stairs#6]
Minecraft v1.19.2
Slabs & Stairs v1.3.0

Deepslate, Concrete, Terracotta, etc slabs break as if using a bare hand. A pickaxe of every type has been tested with the same effect.

**Comment by FrostbyteGames1** [comment]
Thanks for catching that, I'm not sure how we missed it. It should be fixed in version 1.5.1

**Comment by markmoser** [comment]
Will 1.5.1 work on 1.19.2?

This is a create/byg server so I'm locked in at that MC version.

**Comment by FrostbyteGames1** [comment]
I'm not sure, but feel free to test it and let us know. If it doesn't work, we will try to backport to that version.

**Comment by markmoser** [comment]
Not working as downloaded.

```
Unmet dependency listing:

Mod 'Frostbyte's Slabs & Stairs' (slabsandstairs) 1.5.1 requires any version
between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but 
only the wrong version is present: 1.19.2!
```

**Comment by FrostbyteGames1** [comment]
Slabs & Stairs 1.5.1 has been backported to Minecraft 1.19.2 as Slabs & Stairs 1.3.1

**Comment by markmoser** [comment]
Thank you so much!
